-- Bundled Raynna pip WeakAura template. This is a renamed copy of the original Druid Combo points display tables, so fresh installs do not depend on that aura being imported.
RaynnaRotationHelperPipTemplate = {
["Raynna's Pips"] = {
["controlledChildren"] = {
"CP 1",
"CP 2",
"CP 3",
"CP 4",
"CP 5",
"CP1BlackOutline",
"CP2BlackOutline",
"CP3BlackOutline",
"CP4BlackOutline",
"CP5BlackOutline",
"CP1YellowOutline GCD",
"CP2YellowOutline GCD",
"CP3YellowOutline GCD",
"CP4YellowOutline GCD",
"CP5YellowOutline GCD",
},
["borderBackdrop"] = "Blizzard Tooltip",
["wagoID"] = "YsXnwp3E4",
["xOffset"] = -323.63379956615,
["preferToUpdate"] = false,
["yOffset"] = -67.929352127084,
["anchorPoint"] = "CENTER",
["borderColor"] = {
0,
0,
0,
1,
},
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["unit"] = "player",
["type"] = "aura2",
["spellIds"] = {
},
["subeventSuffix"] = "_CAST_START",
["subeventPrefix"] = "SPELL",
["debuffType"] = "HELPFUL",
["event"] = "Health",
["names"] = {
},
},
["untrigger"] = {
},
},
},
["internalVersion"] = 90,
["animation"] = {
["start"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
},
["desc"] = "",
["version"] = 10,
["subRegions"] = {
},
["load"] = {
["use_class"] = "true",
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["spec"] = {
["multi"] = {
},
},
["class"] = {
["single"] = "ROGUE",
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["backdropColor"] = {
1,
1,
1,
0.5,
},
["source"] = "import",
["scale"] = 0.55,
["border"] = false,
["borderEdge"] = "Square Full White",
["regionType"] = "group",
["borderSize"] = 2,
["authorOptions"] = {
},
["borderOffset"] = 4,
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "Druid Combo points",
["config"] = {
},
["frameStrata"] = 1,
["anchorFrameType"] = "SCREEN",
["alpha"] = 1,
["borderInset"] = 1,
["uid"] = "ESfLgjn5jDO",
["parent"] = "Raynna's Feral Druid Rotation Helper",
["conditions"] = {
},
["information"] = {
["showNilIsFalse"] = true,
["ignoreOptionsEventErrors"] = true,
["forceEvents"] = true,
["groupOffset"] = true,
},
["selfPoint"] = "BOTTOMLEFT",
},
["Raynna's Pips - CP 1"] = {
["wagoID"] = "YsXnwp3E4",
["authorOptions"] = {
},
["preferToUpdate"] = false,
["yOffset"] = -165,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["duration"] = "1",
["unit"] = "player",
["powertype"] = 4,
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
["type"] = "unit",
["subeventSuffix"] = "_CAST_START",
["power_operator"] = {
">=",
},
["use_requirePowerType"] = false,
["subeventPrefix"] = "SPELL",
["names"] = {
},
["spellIds"] = {
},
["use_power"] = false,
["unevent"] = "auto",
["event"] = "Power",
["use_unit"] = true,
["power"] = {
"1",
},
},
["untrigger"] = {
},
},
["disjunctive"] = "all",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 42.765598297119,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["regionType"] = "texture",
["blendMode"] = "BLEND",
["xOffset"] = -70,
["texture"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Circle_Smooth_Border",
["color"] = {
0,
0,
0,
1,
},
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP 1",
["parent"] = "Druid Combo points",
["frameStrata"] = 1,
["width"] = 42.76575088501,
["anchorFrameType"] = "SCREEN",
["config"] = {
},
["alpha"] = 1,
["uid"] = "MygDhl8J6CJ",
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["op"] = ">=",
["variable"] = "power",
["value"] = "1",
},
["changes"] = {
{
["value"] = {
0.94509803921569,
0.019607843137255,
0,
1,
},
["property"] = "color",
},
{
["value"] = 1,
["property"] = "alpha",
},
},
},
{
["check"] = {
["trigger"] = 1,
["op"] = "==",
["variable"] = "power",
["value"] = "5",
},
["changes"] = {
{
["value"] = {
1,
0.22352941176471,
0.72156862745098,
1,
},
["property"] = "color",
},
},
},
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
},
["Raynna's Pips - CP 2"] = {
["wagoID"] = "YsXnwp3E4",
["authorOptions"] = {
},
["preferToUpdate"] = false,
["yOffset"] = -165,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["subeventPrefix"] = "SPELL",
["type"] = "unit",
["use_unit"] = true,
["power"] = {
"1",
},
["power_operator"] = {
">=",
},
["duration"] = "1",
["event"] = "Power",
["names"] = {
},
["unevent"] = "auto",
["powertype"] = 4,
["spellIds"] = {
},
["unit"] = "player",
["use_power"] = false,
["subeventSuffix"] = "_CAST_START",
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 42.765598297119,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["regionType"] = "texture",
["blendMode"] = "BLEND",
["xOffset"] = -35,
["texture"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Circle_Smooth_Border",
["color"] = {
0,
0,
0,
1,
},
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP 2",
["parent"] = "Druid Combo points",
["frameStrata"] = 1,
["width"] = 42.76575088501,
["anchorFrameType"] = "SCREEN",
["config"] = {
},
["alpha"] = 1,
["uid"] = "NHOOpGEFL7W",
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["op"] = ">=",
["variable"] = "power",
["value"] = "2",
},
["changes"] = {
{
["value"] = {
0.94509803921569,
0.019607843137255,
0,
1,
},
["property"] = "color",
},
{
["value"] = 1,
["property"] = "alpha",
},
},
},
{
["check"] = {
["trigger"] = 1,
["op"] = "==",
["variable"] = "power",
["value"] = "5",
},
["changes"] = {
{
["value"] = {
1,
0.22352941176471,
0.72156862745098,
1,
},
["property"] = "color",
},
},
},
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
},
["Raynna's Pips - CP 3"] = {
["wagoID"] = "YsXnwp3E4",
["authorOptions"] = {
},
["preferToUpdate"] = false,
["yOffset"] = -165,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["subeventPrefix"] = "SPELL",
["type"] = "unit",
["use_unit"] = true,
["power"] = {
"1",
},
["power_operator"] = {
">=",
},
["duration"] = "1",
["event"] = "Power",
["names"] = {
},
["unevent"] = "auto",
["powertype"] = 4,
["spellIds"] = {
},
["unit"] = "player",
["use_power"] = false,
["subeventSuffix"] = "_CAST_START",
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 42.765598297119,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["regionType"] = "texture",
["blendMode"] = "BLEND",
["xOffset"] = 0,
["texture"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Circle_Smooth_Border",
["color"] = {
0,
0,
0,
1,
},
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP 3",
["parent"] = "Druid Combo points",
["frameStrata"] = 1,
["width"] = 42.76575088501,
["anchorFrameType"] = "SCREEN",
["config"] = {
},
["alpha"] = 1,
["uid"] = "mWc21ADA3tl",
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["op"] = ">=",
["variable"] = "power",
["value"] = "3",
},
["changes"] = {
{
["value"] = {
0.94509803921569,
0.019607843137255,
0,
1,
},
["property"] = "color",
},
{
["value"] = 1,
["property"] = "alpha",
},
},
},
{
["check"] = {
["trigger"] = 1,
["op"] = "==",
["variable"] = "power",
["value"] = "5",
},
["changes"] = {
{
["value"] = {
1,
0.22352941176471,
0.72156862745098,
1,
},
["property"] = "color",
},
},
},
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
},
["Raynna's Pips - CP 4"] = {
["wagoID"] = "YsXnwp3E4",
["authorOptions"] = {
},
["preferToUpdate"] = false,
["yOffset"] = -165,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["duration"] = "1",
["unit"] = "player",
["powertype"] = 4,
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
["type"] = "unit",
["subeventSuffix"] = "_CAST_START",
["power_operator"] = {
">=",
},
["use_requirePowerType"] = false,
["subeventPrefix"] = "SPELL",
["names"] = {
},
["spellIds"] = {
},
["use_power"] = false,
["unevent"] = "auto",
["event"] = "Power",
["use_unit"] = true,
["power"] = {
"1",
},
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 42.765598297119,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["regionType"] = "texture",
["blendMode"] = "BLEND",
["xOffset"] = 35,
["texture"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Circle_Smooth_Border",
["color"] = {
0,
0,
0,
1,
},
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP 4",
["parent"] = "Druid Combo points",
["frameStrata"] = 1,
["width"] = 42.76575088501,
["anchorFrameType"] = "SCREEN",
["config"] = {
},
["alpha"] = 1,
["uid"] = "bj8)zYdmcmX",
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["op"] = ">=",
["variable"] = "power",
["value"] = "4",
},
["changes"] = {
{
["value"] = {
0.94509803921569,
0.019607843137255,
0,
1,
},
["property"] = "color",
},
{
["value"] = 1,
["property"] = "alpha",
},
},
},
{
["check"] = {
["trigger"] = 1,
["op"] = "==",
["variable"] = "power",
["value"] = "5",
},
["changes"] = {
{
["value"] = {
1,
0.22352941176471,
0.72156862745098,
1,
},
["property"] = "color",
},
},
},
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
},
["Raynna's Pips - CP 5"] = {
["wagoID"] = "YsXnwp3E4",
["authorOptions"] = {
},
["preferToUpdate"] = false,
["yOffset"] = -165,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["duration"] = "1",
["unit"] = "player",
["powertype"] = 4,
["use_powertype"] = true,
["debuffType"] = "HELPFUL",
["type"] = "unit",
["subeventSuffix"] = "_CAST_START",
["power_operator"] = {
">=",
},
["use_requirePowerType"] = false,
["subeventPrefix"] = "SPELL",
["names"] = {
},
["spellIds"] = {
},
["use_power"] = false,
["unevent"] = "auto",
["event"] = "Power",
["use_unit"] = true,
["power"] = {
"1",
},
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 42.765598297119,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["regionType"] = "texture",
["blendMode"] = "BLEND",
["xOffset"] = 70,
["texture"] = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\Circle_Smooth_Border",
["color"] = {
0,
0,
0,
1,
},
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP 5",
["parent"] = "Druid Combo points",
["frameStrata"] = 1,
["width"] = 42.76575088501,
["anchorFrameType"] = "SCREEN",
["config"] = {
},
["alpha"] = 1,
["uid"] = "7wcRNpqKcgs",
["conditions"] = {
{
["check"] = {
["trigger"] = 1,
["op"] = ">=",
["variable"] = "power",
["value"] = "5",
},
["changes"] = {
{
["value"] = {
0.94509803921569,
0.019607843137255,
0,
1,
},
["property"] = "color",
},
{
["value"] = 1,
["property"] = "alpha",
},
},
},
{
["check"] = {
["trigger"] = 1,
["op"] = "==",
["variable"] = "power",
["value"] = "5",
},
["changes"] = {
{
["value"] = {
1,
0.22352941176471,
0.72156862745098,
1,
},
["property"] = "color",
},
{
["value"] = 1,
["property"] = "alpha",
},
},
},
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
},
["Raynna's Pips - CP1BlackOutline"] = {
["wagoID"] = "YsXnwp3E4",
["color"] = {
0,
0,
0,
1,
},
["preferToUpdate"] = false,
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["type"] = "unit",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Conditions",
["unit"] = "player",
["spellIds"] = {
},
["subeventPrefix"] = "SPELL",
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 75,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 1",
["regionType"] = "texture",
["blendMode"] = "BLEND",
["parent"] = "Druid Combo points",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["width"] = 75,
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP1BlackOutline",
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["frameStrata"] = 3,
["anchorFrameType"] = "SELECTFRAME",
["config"] = {
},
["uid"] = "s6HbQzHj7eh",
["alpha"] = 1,
["xOffset"] = 0,
["conditions"] = {
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["authorOptions"] = {
},
},
["Raynna's Pips - CP2BlackOutline"] = {
["wagoID"] = "YsXnwp3E4",
["color"] = {
0,
0,
0,
1,
},
["preferToUpdate"] = false,
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["type"] = "unit",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Conditions",
["unit"] = "player",
["spellIds"] = {
},
["subeventPrefix"] = "SPELL",
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 75,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 2",
["regionType"] = "texture",
["blendMode"] = "BLEND",
["parent"] = "Druid Combo points",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["width"] = 75,
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP2BlackOutline",
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["frameStrata"] = 3,
["anchorFrameType"] = "SELECTFRAME",
["config"] = {
},
["uid"] = "EOWc38Eax4K",
["alpha"] = 1,
["xOffset"] = 0,
["conditions"] = {
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["authorOptions"] = {
},
},
["Raynna's Pips - CP3BlackOutline"] = {
["wagoID"] = "YsXnwp3E4",
["color"] = {
0,
0,
0,
1,
},
["preferToUpdate"] = false,
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["type"] = "unit",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Conditions",
["unit"] = "player",
["spellIds"] = {
},
["subeventPrefix"] = "SPELL",
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 75,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 3",
["regionType"] = "texture",
["blendMode"] = "BLEND",
["parent"] = "Druid Combo points",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["width"] = 75,
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP3BlackOutline",
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["frameStrata"] = 3,
["anchorFrameType"] = "SELECTFRAME",
["config"] = {
},
["uid"] = "HUSb)8FnToQ",
["alpha"] = 1,
["xOffset"] = 0,
["conditions"] = {
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["authorOptions"] = {
},
},
["Raynna's Pips - CP4BlackOutline"] = {
["wagoID"] = "YsXnwp3E4",
["color"] = {
0,
0,
0,
1,
},
["preferToUpdate"] = false,
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["type"] = "unit",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Conditions",
["unit"] = "player",
["spellIds"] = {
},
["subeventPrefix"] = "SPELL",
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 75,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 4",
["regionType"] = "texture",
["blendMode"] = "BLEND",
["parent"] = "Druid Combo points",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["width"] = 75,
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP4BlackOutline",
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["frameStrata"] = 3,
["anchorFrameType"] = "SELECTFRAME",
["config"] = {
},
["uid"] = "v7(ANH59PYq",
["alpha"] = 1,
["xOffset"] = 0,
["conditions"] = {
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["authorOptions"] = {
},
},
["Raynna's Pips - CP5BlackOutline"] = {
["wagoID"] = "YsXnwp3E4",
["color"] = {
0,
0,
0,
1,
},
["preferToUpdate"] = false,
["yOffset"] = 0,
["anchorPoint"] = "CENTER",
["url"] = "https://wago.io/YsXnwp3E4/10",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["triggers"] = {
{
["trigger"] = {
["type"] = "unit",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Conditions",
["unit"] = "player",
["spellIds"] = {
},
["subeventPrefix"] = "SPELL",
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["internalVersion"] = 90,
["selfPoint"] = "CENTER",
["desaturate"] = false,
["rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 75,
["rotate"] = true,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["textureWrapMode"] = "CLAMP",
["source"] = "import",
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 5",
["regionType"] = "texture",
["blendMode"] = "BLEND",
["parent"] = "Druid Combo points",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["width"] = 75,
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["semver"] = "1.0.9",
["tocversion"] = 40400,
["id"] = "CP5BlackOutline",
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["frameStrata"] = 3,
["anchorFrameType"] = "SELECTFRAME",
["config"] = {
},
["uid"] = "hiv(HBHvAg9",
["alpha"] = 1,
["xOffset"] = 0,
["conditions"] = {
},
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["authorOptions"] = {
},
},
["Raynna's Pips - CP1YellowOutline GCD"] = {
["user_y"] = 0,
["user_x"] = 0,
["authorOptions"] = {
},
["adjustedMax"] = "",
["yOffset"] = 0,
["foregroundColor"] = {
0.84705882352941,
0.89019607843137,
0.87843137254902,
1,
},
["sameTexture"] = true,
["url"] = "https://wago.io/YsXnwp3E4/10",
["backgroundColor"] = {
0.23921568627451,
0.23921568627451,
0.23921568627451,
0,
},
["selfPoint"] = "CENTER",
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["rotation"] = 0,
["font"] = "Friz Quadrata TT",
["crop_y"] = 0,
["textureWrapMode"] = "CLAMP",
["foregroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["smoothProgress"] = false,
["useAdjustededMin"] = false,
["regionType"] = "progresstexture",
["blendMode"] = "BLEND",
["slantMode"] = "INSIDE",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["compress"] = false,
["alpha"] = 1,
["auraRotation"] = 0,
["backgroundOffset"] = 0,
["wagoID"] = "YsXnwp3E4",
["parent"] = "Druid Combo points",
["adjustedMin"] = "",
["desaturateBackground"] = false,
["desaturateForeground"] = false,
["triggers"] = {
{
["trigger"] = {
["type"] = "spell",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Global Cooldown",
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["spellIds"] = {
},
["use_inverse"] = false,
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_alwaystrue"] = true,
["subeventSuffix"] = "_CAST_START",
["duration"] = "1",
["event"] = "Conditions",
["use_unit"] = true,
["unevent"] = "auto",
["subeventPrefix"] = "SPELL",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["endAngle"] = 360,
["internalVersion"] = 90,
["progressSource"] = {
-1,
"",
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["discrete_rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 63,
["rotate"] = true,
["useAdjustededMax"] = false,
["fontSize"] = 12,
["source"] = "import",
["xOffset"] = 0,
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 1",
["preferToUpdate"] = false,
["tocversion"] = 40400,
["uid"] = "e61)eod)3im",
["conditions"] = {
},
["color"] = {
1,
0.91764705882353,
0,
1,
},
["anchorPoint"] = "CENTER",
["config"] = {
},
["semver"] = "1.0.9",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["id"] = "CP1YellowOutline GCD",
["anchorFrameType"] = "SELECTFRAME",
["frameStrata"] = 4,
["width"] = 63,
["desaturate"] = false,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["inverse"] = true,
["startAngle"] = 0,
["orientation"] = "CLOCKWISE",
["crop_x"] = 0,
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["backgroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura3",
},
["Raynna's Pips - CP2YellowOutline GCD"] = {
["user_y"] = 0,
["user_x"] = 0,
["authorOptions"] = {
},
["adjustedMax"] = "",
["yOffset"] = 0,
["foregroundColor"] = {
0.84705882352941,
0.89019607843137,
0.87843137254902,
1,
},
["sameTexture"] = true,
["url"] = "https://wago.io/YsXnwp3E4/10",
["backgroundColor"] = {
0.23921568627451,
0.23921568627451,
0.23921568627451,
0,
},
["selfPoint"] = "CENTER",
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["rotation"] = 0,
["font"] = "Friz Quadrata TT",
["crop_y"] = 0,
["textureWrapMode"] = "CLAMP",
["foregroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["smoothProgress"] = false,
["useAdjustededMin"] = false,
["regionType"] = "progresstexture",
["blendMode"] = "BLEND",
["slantMode"] = "INSIDE",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["compress"] = false,
["alpha"] = 1,
["auraRotation"] = 0,
["backgroundOffset"] = 0,
["wagoID"] = "YsXnwp3E4",
["parent"] = "Druid Combo points",
["adjustedMin"] = "",
["desaturateBackground"] = false,
["desaturateForeground"] = false,
["triggers"] = {
{
["trigger"] = {
["type"] = "spell",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Global Cooldown",
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["spellIds"] = {
},
["use_inverse"] = false,
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_alwaystrue"] = true,
["subeventSuffix"] = "_CAST_START",
["duration"] = "1",
["event"] = "Conditions",
["use_unit"] = true,
["unevent"] = "auto",
["subeventPrefix"] = "SPELL",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["endAngle"] = 360,
["internalVersion"] = 90,
["progressSource"] = {
-1,
"",
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["discrete_rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 63,
["rotate"] = true,
["useAdjustededMax"] = false,
["fontSize"] = 12,
["source"] = "import",
["xOffset"] = 0,
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 2",
["preferToUpdate"] = false,
["tocversion"] = 40400,
["uid"] = "Ajh4dVnfpYV",
["conditions"] = {
},
["color"] = {
1,
0.91764705882353,
0,
1,
},
["anchorPoint"] = "CENTER",
["config"] = {
},
["semver"] = "1.0.9",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["id"] = "CP2YellowOutline GCD",
["anchorFrameType"] = "SELECTFRAME",
["frameStrata"] = 4,
["width"] = 63,
["desaturate"] = false,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["inverse"] = true,
["startAngle"] = 0,
["orientation"] = "CLOCKWISE",
["crop_x"] = 0,
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["backgroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura3",
},
["Raynna's Pips - CP3YellowOutline GCD"] = {
["user_y"] = 0,
["user_x"] = 0,
["authorOptions"] = {
},
["adjustedMax"] = "",
["yOffset"] = 0,
["foregroundColor"] = {
0.84705882352941,
0.89019607843137,
0.87843137254902,
1,
},
["sameTexture"] = true,
["url"] = "https://wago.io/YsXnwp3E4/10",
["backgroundColor"] = {
0.23921568627451,
0.23921568627451,
0.23921568627451,
0,
},
["selfPoint"] = "CENTER",
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["rotation"] = 0,
["font"] = "Friz Quadrata TT",
["crop_y"] = 0,
["textureWrapMode"] = "CLAMP",
["foregroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["smoothProgress"] = false,
["useAdjustededMin"] = false,
["regionType"] = "progresstexture",
["blendMode"] = "BLEND",
["slantMode"] = "INSIDE",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["compress"] = false,
["alpha"] = 1,
["auraRotation"] = 0,
["backgroundOffset"] = 0,
["wagoID"] = "YsXnwp3E4",
["parent"] = "Druid Combo points",
["adjustedMin"] = "",
["desaturateBackground"] = false,
["desaturateForeground"] = false,
["triggers"] = {
{
["trigger"] = {
["type"] = "spell",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Global Cooldown",
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["spellIds"] = {
},
["use_inverse"] = false,
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_alwaystrue"] = true,
["subeventSuffix"] = "_CAST_START",
["duration"] = "1",
["event"] = "Conditions",
["use_unit"] = true,
["unevent"] = "auto",
["subeventPrefix"] = "SPELL",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["endAngle"] = 360,
["internalVersion"] = 90,
["progressSource"] = {
-1,
"",
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["discrete_rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 63,
["rotate"] = true,
["useAdjustededMax"] = false,
["fontSize"] = 12,
["source"] = "import",
["xOffset"] = 0,
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 3",
["preferToUpdate"] = false,
["tocversion"] = 40400,
["uid"] = "zZJlRgXf6FC",
["conditions"] = {
},
["color"] = {
1,
0.91764705882353,
0,
1,
},
["anchorPoint"] = "CENTER",
["config"] = {
},
["semver"] = "1.0.9",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["id"] = "CP3YellowOutline GCD",
["anchorFrameType"] = "SELECTFRAME",
["frameStrata"] = 4,
["width"] = 63,
["desaturate"] = false,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["inverse"] = true,
["startAngle"] = 0,
["orientation"] = "CLOCKWISE",
["crop_x"] = 0,
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["backgroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura3",
},
["Raynna's Pips - CP4YellowOutline GCD"] = {
["user_y"] = 0,
["user_x"] = 0,
["authorOptions"] = {
},
["adjustedMax"] = "",
["yOffset"] = 0,
["foregroundColor"] = {
0.84705882352941,
0.89019607843137,
0.87843137254902,
1,
},
["sameTexture"] = true,
["url"] = "https://wago.io/YsXnwp3E4/10",
["backgroundColor"] = {
0.23921568627451,
0.23921568627451,
0.23921568627451,
0,
},
["selfPoint"] = "CENTER",
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["rotation"] = 0,
["font"] = "Friz Quadrata TT",
["crop_y"] = 0,
["textureWrapMode"] = "CLAMP",
["foregroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["smoothProgress"] = false,
["useAdjustededMin"] = false,
["regionType"] = "progresstexture",
["blendMode"] = "BLEND",
["slantMode"] = "INSIDE",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["compress"] = false,
["alpha"] = 1,
["auraRotation"] = 0,
["backgroundOffset"] = 0,
["wagoID"] = "YsXnwp3E4",
["parent"] = "Druid Combo points",
["adjustedMin"] = "",
["desaturateBackground"] = false,
["desaturateForeground"] = false,
["triggers"] = {
{
["trigger"] = {
["type"] = "spell",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Global Cooldown",
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["spellIds"] = {
},
["use_inverse"] = false,
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_alwaystrue"] = true,
["subeventSuffix"] = "_CAST_START",
["duration"] = "1",
["event"] = "Conditions",
["use_unit"] = true,
["unevent"] = "auto",
["subeventPrefix"] = "SPELL",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["endAngle"] = 360,
["internalVersion"] = 90,
["progressSource"] = {
-1,
"",
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["discrete_rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 63,
["rotate"] = true,
["useAdjustededMax"] = false,
["fontSize"] = 12,
["source"] = "import",
["xOffset"] = 0,
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 4",
["preferToUpdate"] = false,
["tocversion"] = 40400,
["uid"] = "l2be3AG2Lp1",
["conditions"] = {
},
["color"] = {
1,
0.91764705882353,
0,
1,
},
["anchorPoint"] = "CENTER",
["config"] = {
},
["semver"] = "1.0.9",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["id"] = "CP4YellowOutline GCD",
["anchorFrameType"] = "SELECTFRAME",
["frameStrata"] = 4,
["width"] = 63,
["desaturate"] = false,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["inverse"] = true,
["startAngle"] = 0,
["orientation"] = "CLOCKWISE",
["crop_x"] = 0,
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["backgroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura3",
},
["Raynna's Pips - CP5YellowOutline GCD"] = {
["user_y"] = 0,
["user_x"] = 0,
["authorOptions"] = {
},
["adjustedMax"] = "",
["yOffset"] = 0,
["foregroundColor"] = {
0.84705882352941,
0.89019607843137,
0.87843137254902,
1,
},
["sameTexture"] = true,
["url"] = "https://wago.io/YsXnwp3E4/10",
["backgroundColor"] = {
0.23921568627451,
0.23921568627451,
0.23921568627451,
0,
},
["selfPoint"] = "CENTER",
["desc"] = "Rogue Combo Points - Classic WoW                                                              - created by Johadan                                                                                                                        - https://wago.io/p/Johadan#1650                                                                                         - Discord: https://discord.gg/QJs5SHH",
["rotation"] = 0,
["font"] = "Friz Quadrata TT",
["crop_y"] = 0,
["textureWrapMode"] = "CLAMP",
["foregroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["smoothProgress"] = false,
["useAdjustededMin"] = false,
["regionType"] = "progresstexture",
["blendMode"] = "BLEND",
["slantMode"] = "INSIDE",
["texture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura73",
["compress"] = false,
["alpha"] = 1,
["auraRotation"] = 0,
["backgroundOffset"] = 0,
["wagoID"] = "YsXnwp3E4",
["parent"] = "Druid Combo points",
["adjustedMin"] = "",
["desaturateBackground"] = false,
["desaturateForeground"] = false,
["triggers"] = {
{
["trigger"] = {
["type"] = "spell",
["unevent"] = "auto",
["duration"] = "1",
["event"] = "Global Cooldown",
["unit"] = "player",
["subeventPrefix"] = "SPELL",
["spellIds"] = {
},
["use_inverse"] = false,
["use_unit"] = true,
["subeventSuffix"] = "_CAST_START",
["names"] = {
},
["debuffType"] = "HELPFUL",
},
["untrigger"] = {
},
},
{
["trigger"] = {
["type"] = "unit",
["use_alwaystrue"] = true,
["subeventSuffix"] = "_CAST_START",
["duration"] = "1",
["event"] = "Conditions",
["use_unit"] = true,
["unevent"] = "auto",
["subeventPrefix"] = "SPELL",
["unit"] = "player",
},
["untrigger"] = {
},
},
["disjunctive"] = "any",
["activeTriggerMode"] = -10,
},
["endAngle"] = 360,
["internalVersion"] = 90,
["progressSource"] = {
-1,
"",
},
["animation"] = {
["start"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "    function(progress, start, delta)\n      return start + (progress * delta)\n    end\n  ",
["use_alpha"] = true,
["type"] = "none",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
["main"] = {
["type"] = "none",
["easeStrength"] = 3,
["duration_type"] = "seconds",
["easeType"] = "none",
},
["finish"] = {
["colorR"] = 1,
["duration"] = "0.1",
["alphaType"] = "straight",
["colorA"] = 1,
["colorG"] = 1,
["alphaFunc"] = "function(progress, start, delta)\n    return start + (progress * delta)\nend\n",
["use_alpha"] = true,
["type"] = "custom",
["easeType"] = "none",
["scaley"] = 1,
["alpha"] = 0,
["y"] = 0,
["x"] = 0,
["scalex"] = 1,
["preset"] = "fade",
["easeStrength"] = 3,
["rotate"] = 0,
["colorB"] = 1,
["duration_type"] = "seconds",
},
},
["discrete_rotation"] = 0,
["version"] = 10,
["subRegions"] = {
{
["type"] = "subbackground",
},
},
["height"] = 63,
["rotate"] = true,
["useAdjustededMax"] = false,
["fontSize"] = 12,
["source"] = "import",
["xOffset"] = 0,
["mirror"] = false,
["anchorFrameFrame"] = "WeakAuras:CP 5",
["preferToUpdate"] = false,
["tocversion"] = 40400,
["uid"] = "oijEvRxH6NM",
["conditions"] = {
},
["color"] = {
1,
0.91764705882353,
0,
1,
},
["anchorPoint"] = "CENTER",
["config"] = {
},
["semver"] = "1.0.9",
["actions"] = {
["start"] = {
},
["init"] = {
},
["finish"] = {
},
},
["id"] = "CP5YellowOutline GCD",
["anchorFrameType"] = "SELECTFRAME",
["frameStrata"] = 4,
["width"] = 63,
["desaturate"] = false,
["load"] = {
["use_class"] = true,
["use_never"] = false,
["talent"] = {
["multi"] = {
},
},
["zoneIds"] = "",
["class"] = {
["single"] = "DRUID",
["multi"] = {
},
},
["spec"] = {
["multi"] = {
},
},
["size"] = {
["multi"] = {
},
},
},
["inverse"] = true,
["startAngle"] = 0,
["orientation"] = "CLOCKWISE",
["crop_x"] = 0,
["information"] = {
["showNilIsFalse"] = true,
["forceEvents"] = true,
["ignoreOptionsEventErrors"] = true,
},
["backgroundTexture"] = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\Aura3",
},
}
